### ISSUE TITLE
Errors during scheduled Versions update

### ISSUE THREAD

**Issue by badtou** [fHDHR/fHDHR#138] opened 2021-02-26 14:18 UTC
The following is an error I am seeing during a scheduled epg update, and it shows that it ran 3 times before it decided to fail.  I've seen this on two different VMs so something is going on here.

2021-02-25 22:09:50,115] NOOB - Updating plutotv EPG cache.
[2021-02-25 22:09:53,872] NOOB - Wrote plutotv EPG cache. 41325 Programs for 285 Channels
[2021-02-25 22:09:53,876] INFO - Sending Alive message to network.
[2021-02-25 22:39:54,133] NOOB - Updating plutotv EPG cache.
[2021-02-25 22:39:57,935] NOOB - Wrote plutotv EPG cache. 41325 Programs for 285 Channels
[2021-02-25 22:39:57,943] INFO - Sending Alive message to network.
[2021-02-25 23:09:58,167] NOOB - Updating plutotv EPG cache.
[2021-02-25 23:10:01,857] NOOB - Wrote plutotv EPG cache. 41325 Programs for 285 Channels
[2021-02-25 23:10:01,862] INFO - Sending Alive message to network.
Traceback (most recent call last):
  File "/home/james/PlutoTV/main.py", line 16, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web))
  File "/home/james/PlutoTV/fHDHR/cli/run.py", line 127, in main
    returned_code = start(args, script_dir, fHDHR_web)
  File "/home/james/PlutoTV/fHDHR/cli/run.py", line 107, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler)
  File "/home/james/PlutoTV/fHDHR/cli/run.py", line 52, in run
    fhdhr.scheduler.run()
  File "/home/james/PlutoTV/fHDHR/scheduler/__init__.py", line 13, in run
    self.schedule.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/api/versions?method=check': No schema supplied. Perhaps you meant http:///api/versions?method=check?
[2021-02-26 00:00:19,541] INFO - 172.17.201.33 - - [2021-02-26 00:00:19] "GET /api/xmltv?method=get&source=plutotv HTTP/1.1" 200 17624466 3.760700

**Comment by deathbybandaid** [comment] 2021-02-26 17:06
the issue isn't related to the xmltv, but to the Versions API. I'll push a patch soon

**Comment by badtou** [comment] 2021-02-26 20:58
It may be fixed in Ubuntu as it hasn't failed there yet, but I just received a failure in Windows 10 which is likely caused by the firewall preventing a connection to the localhost address, and this could be resolve by using the hostname rather than localhost.  
By the way. I've also been using MSSQL for a database which is considerably faster.

  File "C:\Users\james\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /api/versions?method=check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000139252A4790>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))

**Comment by deathbybandaid** [comment] 2021-02-26 21:13
Error is safe to ignore until I push a fix. Just will pop up every 2-3 hours

**Comment by deathbybandaid** [comment] 2021-02-27 12:59
I just pushed another fix for this, that likely will kill the issue

**Closed as completed** 2021-02-27 22:02 UTC
Labels: bug, Believed to be fixed
